### ISSUE TITLE
[BUG]  rtorrent showing incorrect partial downloads percentages

### ISSUE THREAD

**Issue by TheTrustyHammer** [swizzin/swizzin#1106]
### What happened?

Steps to reproduce:

1. Install package '...' Rtorrent, latest swizzing
2. Go to '....' download partial torrent
3. Error '...' it stalls and shows incorrect % of finished even though its 100%. Rtorrent github says its a swizzin issue....

Expected results:

### Swizzin commit

5253f36

### What OS are you using?

Debian 12 (Bookworm)

### What architecture is your OS?

amd64

**Comment by THELASTOFUS** [comment]
![image](https://github.com/swizzin/swizzin/assets/5510687/25327c07-adca-4f06-9e5e-acb9dea583c1)

**Comment by THELASTOFUS** [comment]
Torrent shows 100% and yet the file is at 75.7%. CRC32 check shows 100% match with file downloaded...very annoying BUG

![image](https://github.com/swizzin/swizzin/assets/5510687/bf32df27-ab8e-44af-ab7a-6e72becd6b20)

**Comment by stickz** [comment]
Thank you for the bug report. I have reported the piece boundary problem to the author. 

1. Our first option would be to resolve the problem with the authors' support.
2. Our second option would be to remove the patch. Since it fixes one problem and creates anther.

**Comment by THELASTOFUS** [comment]
Thank you. I hope we can resolve this - as a new user to swizzin - this confused the bajeesus out of me.

**Comment by kannibalox** [comment]
I'm working on reproducing this right now, it doesn't look like there's an easy way to get exact file sizes out of ruTorrent, but if you have access to both those and the piece size (called "chunk size" in the "Chunks" tag), that would really help.

**Comment by THELASTOFUS** [comment]
Issue seems to be happening fairly easily to me if I just partial download a torrent with 1 thing as set to download. it also happens on other torrents easily

Definitely a swizzin issue with rtorrent because this doesn't happen not using swizzin to install ru/rtorrent.

not sure what you need from chunk size in the chunk tags 

but for example for a file thats 57.26GB it will say it downloaded 99.8%-99.7% of things....Chunk size says 8192KiB / chunks count 7330 though in this case downloaded shows 100% - but individual files under "files" show 99.6-99.8%.

The one above - i deleted before your response - sorry.

**Comment by stickz** [comment]
Thanks @THELASTOFUS. This information is helpful. We will get this sorted out. The impact of reporting improper progress is cosmetic and limited to the files tab. The author just requires some time to make this issue happen and test a fix.

**Comment by kannibalox** [comment]
I would recommend reverting this for now. I spent a long time banging my head against this problem before realizing the file chunk range calculation is incorrect. I plan to fix it, but it may have actual impact on behavior, so I plan to test it thoroughly. Nothing major, but just more than the cosmetic issue this was intended to fix.

**Comment by stickz** [comment]
Okay thanks will do.
