### ISSUE TITLE
Autodl not working after box update

### ISSUE THREAD

**Issue by LaMpiR** [swizzin/swizzin#419]
## Bug description
I have updated the Swizzin to the latest version with "box update" and after, autodl is not working. Autodl is not shown in rutorrent. Removed it and tried to install again. I get this

`root@xxx:~# box install autodl
Installing autodl
Performing installation of 10 apt packages (irssi screen unzip libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libjson-perl libjson-xs-perl libxml-libxslt-perl)
Error: apt failed. Please consult errors above and/or in the log.`

## Reproduction steps
1. Type box install autodl

## Installed applications through swizzin
rutorrent, plex, sonarr and everything for the server

## Expected behavior
To install autodl.

## Server Info
**(please complete the following information):**
- Ubuntu server 20.04. (OVH)

## Is Swizzin up to date?
Yes.
HEAD is now at 65f8719 updated css aesthetics to address overlapping
Already up to date.

I haven't found anything in install and swizzin log about it.

**Comment by liaralabs** [comment]
There should be command output for the failed apt command. It would likely be near the absolute bottom of `/root/logs/swizzin.log` if this were the last action taken by your user.

Otherwise, you can likely debug the `apt` issue by using a command like `apt update` or `apt install -f`. `apt` is either likely locked or in some broken state which is why it's refusing to install packages. Using one of these commands would likely state exactly why it's not working.

**Comment by LaMpiR** [comment]
There is some error with grub and many users are experiencing this. Unfortunately, because of that, I cannot install autodl...


Errors were encountered while processing:
 grub-efi-amd64-signed

**Comment by liaralabs** [comment]
This apt error is outside the scope of swizzin. You would need to resolve this apt issue yourself to fix apt failing.
