### ISSUE TITLE
GCP: Unexplained Cryptocurrency Mining from VM

### ISSUE THREAD

**Issue by earendildev** [swizzin/swizzin#442]
## Bug description
I am using GCP to host my VM and install Swizzin. 

Last month, after an update, my project and VM was suspended due to a Violation of the Terms of Service by mining cryptocurrency from VM. As much as I want to help out, I haven't installed `xmrig` as a way of donation, due to GCP's Terms of Service.
The suspension was revered a day later.

Today the same thing happened with a brand new VM I created yesterday and installed the lasted update of Swizzin.
For some reason it seems, the `xmrig` software is being installed automatically and is mining when the VM is idle.

I cannot check the logs as my entire project is suspended.

## Reproduction steps
Swizzin installed perfectly with basic applications.

## Installed applications through swizzin
1. Panel
2. Nginx
3. DuckDNS
4. Letsencrypt
5. Deluge

## Expected behavior
No Cryptocurrency mining application being installed without me knowing resulting in suspension of GCP project.

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04
 - Image Source: Ubuntu minimal from GCP

## Is Swizzin up to date?
Yes.

## Additional context
Unable to access due to suspension of Project and VM.

**Comment by liaralabs** [comment]
`xmrig` will never be installed without your consent by way of swizzin. As the project is open source and written in bash, this can be verified by anyone with enough knowledge to read through the scripts (or do a search through the project for xmrig). It is known that cryptocurrency miners are invasive, resource intensive and against the terms of service of practically every VPS provider in existence -- that is why it is opt-in. Furthermore, not everyone can spare CPU cycles in addition to their resource needs from their CPU in the first place.

A quick overview of all the times xmrig is mentioned in the project:

https://i.imgur.com/i1CSA9w.png

xmrig is contained to the files it should be contained to.

If swizzin did install xmrig there would be a couple ways of telling it was installed by swizzin:
- `/usr/local/bin/xmrig` binary location
- Running as your user inside a screen called xmrig
- Running on a config inside the directory `/home/username/.xmrig/config.json`
- Furthermore, it requires configuration to setup things like the pool and wallet address to set up for the miner.
- /etc/systemd/system/xmrig.service -- since users install xmrig with consent, there is no reason to hide services or do sneaky things like restart the miner if it is stopped. This is your server and the scripts respect that.

The install/swizzin logs would have shown if xmrig was installed by swizzin, but it seems as if you have no access to any logging of any sort at this point, so that's a bit unfortunate.

That said, it doesn't actually require root to install a miner, all an attacker would need to do is compromise any user account on the server or already have local access to the server (i.e. have you shared the server with friends?). How strong is your password? Did you use the same password on your reinstall? If the attacker was able to figure out your password and you re-used the same one, you could have essentially just reset your server but left the point of access open.

I will break down the apps you installed:
- Panel
  - Panel runs as swizzin user with a few elevated privileges for sudo `quota` and `systemctl` actions. The panel does not have permission to install applications through `box`; furthermore, any action requiring `systemctl` (start, stop, etc) have their inputs validated and require user authentication to fire from the panel api.
- nginx
  - nginx is acting as a proxy/webserver and has no sudo permissions -- nearly all nginx endpoints require basic authentication to access and as far as I'm aware no applications can be exploited over nginx. Were applications vulnerable, this would be an upstream report as swizzin merely packages applications, not write them (with the exception of the panel).
- Deluge
  - Deluge runs as your user, deluge-web can only be accessed (by default) over localhost and is proxied over nginx to be secured over port 443 with SSL and basic authentication
- Lets Encrypt
  - LE is a one-time script which installs acme.sh and issues a certificate signing request. The LE script is never directly called after this. acme.sh installs a cronjob as root to ensure that cert renewals are seamlessly done without intervention. acme does run as root; however swizzin does not modify or maintain acme -- it is installed directly from acme and is not modified.
- DuckDNS
  - DuckDNS is a script similar to LE. It is essentially a script that's constructed during install with your subdomain and DuckDNS token and then attached a cronjob

In short, as far as I'm aware, there's no vulnerabilities in the applications you've installed. That said, I've pushed a few commits to further harden and restrict the `swizzin` user's permissions further; however, they are just further precautions and I am not aware of any exploits that could let a potential attack even get as far as needing the permissions ascribed to the user in the first place.

Likely suspects may come down to some security and hardening things that are just outside the scope of swizzin:
- root ssh login
- ssh private/public keypairs
- strong passwords, without password reuse
  - if you are concerned your account is compromised, you should start afresh with a new password. The attacker could potentially already have your user account which is a valuable piece of information
  - even if you provisioned a server on a new IP, if you update the IP via DuckDNS, the attacker could potentially follow you to the new IP using your DNS

Do you remember if the process was `xmrig` directly or some other miner? Cryptojacking often involves pulling in payload script from a known endpoint, running it (usually as root), installing cronjobs and/or other back doors to ensure that things such as:
- the process restarts itself if stopped
- the process is hidden from task managers
- the process is named as some other seemingly innocuous service, like `kswapd0` or even `behash`
- backdoor access to the server is maintained so that the attacker can retain access if root passwords or their logins are removed from the server so they can re-infect the server

swizzin would never do any of the above since `xmrig` would be installed with your consent, intentionally on the server.

**Comment by earendildev** [comment]
@liaralabs 
Thank You for your detailed reply.

Honestly I love what you've done with Swizzin, including the new direction, Design wise..
Pretty awesome work.

I really have no idea about this issue..
Maybe it was downloading torrents that brought up the red flag on GCP?
The amount of downloads that was happening continuously must have triggered something...

***

In anycase, Thank you for Swizzin.
