### ISSUE TITLE
Netdata remover can leave netdata processes running behind

### ISSUE THREAD

**Issue by flying-sausages** [swizzin/swizzin#593]
## Bug description
After removing netdata, updater processes keep running behind.
The process should follow this guide instead https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall

## Reproduction steps
1. Install netdata
2. remove netdata
3. Find running netdata updater processes

## Installed applications through swizzin
(e.g. Nginx, ffmpeg, panel)

## Expected behavior
Full removal with nothing left behind

## Server Info
**(please complete the following information):**
 - OS: (e.g. Debian 10, Ubuntu 20.04)
 - Arch: 
 - Image Source: (e.g. "Vanilla download" or "Installscript from specific provider")

## Is Swizzin up to date?
(Please run `box update`, and report whether that was succesful. Please try to reproduce your issue) again. mention the commit hash you are seeing)

(e.g. HEAD is now at d4d151b)

## Additional context
(Add any other context about the problem here. Logs, terminal output, etc.)

(Good sources for log output could be the following: (only if they have relevant information))
- `cat /root/logs/install.log`
- `cat /root/logs/swizzin.log`
- `cat /var/logs/nginx/error.log`
- `systemctl status <app>@<(user)>`
- `journalctl -xe`

**(Please paste your code into code blocks using the codeblock format like below)**

(For logs of 50+ lines, please rehost to a paste hoster like 0bin)

 ```
 ... logs ...
 ```

**Comment by XantherBanter** [comment]
Ayo! Here's more info needed.

## Bug description
After removing netdata, updater processes keep running behind which pins the IO of the disk.

The process should follow this guide instead https://learn.netdata.cloud/docs/agent/packaging/installer/uninstall

## Reproduction steps
Steps to reproduce the behavior:

1. Install netdata (sudo box install netdata)
2. remove netdata (sudo box remove netdata)
3. Find running netdata updater processes

Found the following line under iotop which pins IO

`find / -type d ( -path /sys -o -path /proc -o -path /dev ) -prune -false -o -path *netdata/.environment -type f` which is part of Netdata Updater.`

## Installed applications through swizzin
* nginx
* netdata
* sonarr
* radarr
* panel
* bazarr
* PMS
* librespeed

## Expected behavior
Complete removal of Netdata from the machine.

## Server Info
 - OS: Debian 10
 - Arch: 64-bit
 - Image Source: Walkerservers

## Is Swizzin up to date?
Yes. HEAD is now set to 96724b7

## Additional context

Output of netdata uninstall script: https://ybin.me/p/028f45295ad0a228#Wp2VxcEs37c3ObFbeYZN7jDdC95eME8/JILPt/F9YxI=

* Change netdata script to run `${NETDATA_PREFIX}/usr/libexec/netdata/netdata-uninstaller.sh --yes --env /etc/netdata/.environment` and remove netdata lockfile after. No need to define any env params prior to uninstallation.

**Comment by liaralabs** [comment]
This has been merged to master
