### ISSUE TITLE
[BUG]  - Calibre Web (Develop) Systemd Invalid Flag `-f` | `-f` flag removed

### ISSUE THREAD

**Issue by bakerboy448** [swizzin/swizzin#735]
### What happened?

Calibre Web systemd is using `-f` which is an invalid flag.  Was this actually tested?

https://github.com/swizzin/swizzin/blob/69363a08b70908a728b7d64a1855a0ce7cb2fb27/scripts/install/calibreweb.sh#L119

### Swizzin commit

69363a08b70908a728b7d64a1855a0ce7cb2fb27

### What OS are you using?

Ubuntu 20.04

### What architecture is your OS?

amd64

### Relevant logs and output

```plaintext
bakerboy448@hetz-baker-2004:~$ /opt/.venv/calibreweb/bin/python3 /opt/calibreweb/cps.py -f
usage: cps.py [-h] [-p path] [-g path] [-c path] [-k path] [-v] [-i ip-address] [-s user:pass]
cps.py: error: unrecognized arguments: -f
```

**Comment by liaralabs** [comment]
Thanks for the report against the develop branch of swizzin. As you may be aware, development branches can have issues and may be in a generally more broken state than the stable branch, since this is where we go to introduce features which may not be completely ready to be labelled stable yet. This is the danger of running develop.

That said, contributions from valued users like you help make sure that bugs like this get the attention they deserve.

> Was this actually tested?

I can see how you might be thinking that at this point, but rest assured several folks over the lifetime of this PR have installed and reported back success. Most strangely, the [calibre-web wiki](https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface) still lists `-f` as an option. So that indeed is a bamboozle. In fact, I just tested the script straight from develop and it appears to work perfectly fine and the flag is indeed present out of the box.

```
root@testing:/opt/calibreweb# /opt/.venv/calibreweb/bin/python cps.py --help
usage: cps.py [-h] [-p path] [-g path] [-c path] [-k path] [-v] [-i ip-address] [-s user:pass] [-f]

Calibre Web is a web app providing a interface for browsing, reading and downloading eBooks

optional arguments:
  -h, --help     show this help message and exit
  -p path        path and name to settings db, e.g. /opt/cw.db
  -g path        path and name to gdrive db, e.g. /opt/gd.db
  -c path        path and name to SSL certfile, e.g. /opt/test.cert, works only in combination with keyfile
  -k path        path and name to SSL keyfile, e.g. /opt/test.key, works only in combination with certfile
  -v, --version  Shows version number and exits Calibre-web
  -i ip-address  Server IP-Address to listen
  -s user:pass   Sets specific username to new password
  -f             Enables filepicker in unconfigured mode
  ```

I'm not sure what could be going wrong with your install. Have you modified your installation somehow?

**Comment by bakerboy448** [comment]
Ah, you know what!

I did switch it over to the develop branch for calibre-web.

So seems -f is removed in their develop branch.   Consider this beta testing inception then and - similar to bazarr - calibre web will need updating for future proofing; along with an update script.

`/opt/calibreweb$ /opt/.venv/calibreweb/bin/python cps.py -v
Calibre-Web version: 0.6.13 Beta -2021-08-15T12:43:19+02:00`

**Comment by flying-sausages** [comment]
https://github.com/janeczku/calibre-web/commit/afa585eb65b6a99fb229badcf245d449f4357e2d

**Comment by bakerboy448** [comment]
Why was this closed? It will still be an issue in the next Calibre web version.  This still needs to be addressed in Swizzin.

> help='Flag is depreciated and will be removed in next version')

**Comment by flying-sausages** [comment]
wrong button

**Comment by userdocs** [comment]
fixed with https://github.com/swizzin/swizzin/pull/791
