### ISSUE TITLE
[BUG] autodl-irssi is not working after clean install

### ISSUE THREAD

**Issue by Ob1w4** [swizzin/swizzin#809]
### What happened?

**Steps to reproduce:**

1. Install autodl-irssi
2. Launch ruTorrent
3. The following message appears in the ruTorrent log: <code>autodl-irssi: _initi2: ex:Exception info: No content elem with id autodl-prefs-contents-upload</code> and autodl-irssi can't be used (the button to launch is is missing)

![sqe](https://user-images.githubusercontent.com/89661987/147861855-838eae22-1b9f-4fb9-a15d-74918bd4bf51.jpg)

**Expected results:**

Be able to use autodl-irssi normally

I tried Swizzin on a clean install of Debian 11, without installing anything else. ruTorrent is working normally. But autodl-irssi is not for some reasons.

### Swizzin commit

d1a35a7

### What OS are you using?

Debian 11 (Bullseye)

### What architecture is your OS?

amd64

**Comment by liaralabs** [comment]
This is a known issue due to a recent commit in ruTorrent, where upgrading the version of jQuery has caused AutoDL to break. There was an announcement in the Discord with a workaround to revert to the most recent commit before the breakage:

```
sudo git -C /srv/rutorrent/ checkout 6bffcb1d3fd0a25dcba9100a6bbbc6cb8de7af29
```

We will be fixing this in time if the ruTorrent dev does not respond to the issue; however, with the holidays, dev time for swizzin as been a bit short

**Comment by liaralabs** [comment]
Mitigated for now with 9ef08072450a0a3561e04c3e82fc8fe76e7b5f7e
